### ISSUE TITLE
[Bug]: Overrides standard components in Filament

### ISSUE THREAD

**Issue by ekandreas** [saade/filament-adjacency-list#13]
### What happened?

Our ordinary classes like buttons is overrided with white background with this plugin.

### How to reproduce the bug

When I install the plugin

### Package Version

3.1.0

### PHP Version

8.1

### Laravel Version

10

**Comment by saade** [comment]
are you sure this plugin is causing this? it ships with no css at all

**Comment by saade** [comment]
Hey, i don't think this is related to this package, so i'm closing it, feel free to reach me if you still think this is a problem.

**Comment by ekandreas** [comment]
Yes, you can close it. We will not use the package since it is not possible for us to use with that css impact.

**Comment by saade** [comment]
> Yes, you can close it. We will not use the package since it is not possible for us to use with that css impact.

As i said earlier, i don't think this package is causing issues with your CSS, BUT if you still think its this package that's causing issues, please reopen this with a proof.

You're the only person that reported this issue.

Inspect the affected element and the highlighted example should say "filament-adjacency-list-styles.css"
![image](https://github.com/saade/filament-adjacency-list/assets/14329460/9e7598a3-d8a0-43f7-ab68-58be817bf63a)

**Comment by saade** [comment]
I've removed the filament default css from this package (even if it should not cause any issues), please try `v3.1.1`.
