### ISSUE TITLE
[Bug]: Cannot Reorder, Undefined array key "children"

### ISSUE THREAD

**Issue by ufukseyithan** [saade/filament-adjacency-list#16]
### What happened?

I cannot reorder my items in the list, or make an item a subitem. I can create a child perfectly fine though.

The data in the database is this:
`{"f692b5e5-2cc9-41ad-9b5a-79ea86d1f0b4":{"label":"lol","children":[],"url":null},"4a463f2d-e261-4fb7-bb1b-f130c9cdea64":{"label":"lol2","children":[],"url":null}}`

I am using this form on a settings page ([package](https://filamentphp.com/plugins/filament-spatie-settings))

### How to reproduce the bug

No idea to be honest. It might be because i am doing it in a settings page.

### Package Version

3.1.0

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Windows

**Comment by saade** [comment]
Hey @ufukseyithan, sorry to hear that,

I cannot reproduce this in my current repo, could you please provide a reproduction repository so i can test and debug? Thanks

**Comment by ufukseyithan** [comment]
So I just tested it on a normal resource form in the same project and it works perfectly fine. There is some problem with a "settings" page created with the package I gave a link to in the OP. Would you please be able to test it on that specific package, creating a settings page and putting a adjacency list field to the form?
