### ISSUE TITLE
[Bug]: Error in create resource

### ISSUE THREAD

**Issue by cmayorgahilario** [saade/filament-adjacency-list#4]
### What happened?

Add in form 

```php
public static function form(Form $form): Form
    {
        return $form
            ->schema([
                AdjacencyList::make('Subjects')
                    ->form([
                        Forms\Components\TextInput::make('name')
                            ->required(),
                    ])
                ->labelKey('name')
            ]);
    }
```

![image](https://github.com/saade/filament-adjacency-list/assets/4119035/563aa251-f38c-4cb6-8440-c1354795066d)

![image](https://github.com/saade/filament-adjacency-list/assets/4119035/f300f04e-0e26-4f17-9e49-d89aef6a9936)

![image](https://github.com/saade/filament-adjacency-list/assets/4119035/90160e7e-480e-4e61-bc47-a2cdf620fbdb)

`Illuminate\Database\Grammar::parameterize(): Argument #1 ($values) must be of type array, string given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 1040`

### How to reproduce the bug

> Create new resource

> Add items

> Save resource

### Package Version

3.0.3

### PHP Version

8.2.9

### Laravel Version

10.20.0

### Which operating systems does with happen with?

Linux

**Comment by saade** [comment]
can you share your model?

**Comment by cmayorgahilario** [comment]
```php
<?php

namespace App\Models\Simulation;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

class Subject extends Model
{
    use HasFactory;
    use HasRecursiveRelationships;

    protected $table = "simulation_subjects";
}


```

**Comment by saade** [comment]
relationship support is not merged yet, [see](https://github.com/saade/filament-adjacency-list/pull/3)

will be released by the end of tomorrow.
